name: dioc_generator
description: A generator of code for dioc containers.
version: 1.0.2
homepage: https://github.com/aloisdeniel/dioc
author: Aloïs Deniel <alois.deniel@outlook.com>

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^1.2.0
  build: ^2.0.0
  dart_style: ^2.0.0
  source_gen: ^1.0.0
  code_builder: ^3.7.0
  build_runner: ^1.12.1
  built_collection: ^5.0.0
  dioc:
    git:
      url: https://github.com/ligastavok/flutter_packages.git
      path: dioc/dioc
      ref: v1.x

dev_dependencies:
  test: ^1.16.8
