name: dioc_generator
description: A generator of code for dioc containers.
version: 0.1.6
homepage: https://github.com/aloisdeniel/dioc
author: Aloïs Deniel <alois.deniel@outlook.com>

environment:
  sdk: '>2.0.0-dev <3.0.0'

dependencies:
  analyzer: 0.39.17
  build: 1.3.0
  dart_style: 1.3.6
  source_gen: 0.9.6
  code_builder: 3.5.0
  build_runner: 1.10.2
  built_collection: '>=3.0.0 <5.0.0'
  dioc:
    git:
      url: https://github.com/ligastavok/flutter_packages
      path: dioc/dioc
      # ref: a6d2a37

dev_dependencies:
  test: ^1.15.7
