name: dioc_generator
description: A generator of code for dioc containers.
version: 1.0.0-nullsafety.0
homepage: https://github.com/aloisdeniel/dioc
author: Aloïs Deniel <alois.deniel@outlook.com>

publish_to: none

environment:
  sdk: '>2.12.0-0 <3.0.0'

dependencies:
  analyzer: ^1.0.0
  build: ^1.6.3
  dart_style: ^1.3.13
  source_gen: ^0.9.10+3
  code_builder: ^3.6.0
  build_runner: ^1.11.5
  built_collection: ^5.0.0
  dioc:
    path: ../dioc

dev_dependencies:
  test: ^1.16.3
