name: dioc_example
publish_to: none

environment:
  sdk: '>=2.11.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dioc:
    git:
      url: https://github.com/ligastavok/flutter_packages.git
      path: dioc/dioc
      ref: v1.x

dev_dependencies:
  build: ^2.0.0
  build_runner: ^1.12.1
  dioc_generator:
    path: ../../dioc_generator
