version: 2.1
executors:
  flutter_sdk_image:
    docker:
      - image: cirrusci/flutter:v1.5.4-hotfix.2

orbs:
  codecov: codecov/codecov@1.0.4

jobs:
  build:
    executor: flutter_sdk_image
    steps:
      - checkout
      - run: flutter packages get
      - run: flutter doctor
      - run: dartfmt --set-exit-if-changed .
      - run: dartanalyzer --fatal-infos --fatal-warnings . || exit $?
      - run: flutter test --coverage --coverage-path=coverage/lcov.info
      - codecov/upload:
          file: 'coverage/lcov.info'